### ISSUE TITLE
Connection to SFTP server fails with "Too many authentication failures" despite having selected proper ssh key file

### ISSUE THREAD

**Issue by manuel-koch** [iterate-ch/cyberduck#13675]
**Describe the bug**
I have many ssh keys to access various servers.
I'm not able to connect to a SFTP server anymore in Cyberduck because of error "Too many authentication failures".

**To Reproduce**
1. Double clicking the SFTP bookmark of my SFTP server
2. Dialog pops up with message "Login fehlgeschlagen. Too many authentication failures. Bitte kontaktieren Sie Ihren Webhoster für weitere Hilfestellung."
3. Correct user name is already filled, password field is empty
4. Selecting the proper ssh Key/ID file for connection
5. Clicking "Login"
6. Error happens again

**Expected behavior**
Since I can connect to SSH/SFTP using the dedicated ssh key on console/shell I suspect an error in Cyberduck.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.4 ( Intel CPU )
 - Cyberduck Version 8.4.2 (38090)

**Log Files**
Enabling "Erweitertes Log aktivieren" in the Cyberduck settings prevents the popup dialog mentioned above, but instead another dialog pops up with a same issue underlying issue of "Verbindung fehlgeschlagen" and I can click "Erneut versuchen" or "Netzwerk Diagnose".

Substituted private/confidential information in log file with "MY_..." text
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/9381017/cyberduck.log)
.

**Comment by jonathandhn** [comment]
I'm on the same boat, since the Version 8.4.3 (38269) Apple silicon, not MAS version.

**Comment by sbol-coolblue** [comment]
We're seeing a related (possible the same) issue as well in our logs, when CyberDuck clients are connecting to an SFTP server provided by AWS Transfer Family: despite filling in a username/password, we see multiple authentication requests coming in using the public key authentication method, before it switches to the password method. Looks like a bug on Cyberduck's end - will try to verify using older versions.

**Comment by dkocher** [comment]
Duplicate for #13442.

**Comment by asmaloney** [comment]
@dkocher I don't think this is a duplicate - this issue is for SSH key without a password, the other issue is when using a password.

I misread it as well when I added [my comment](https://github.com/iterate-ch/cyberduck/issues/13442#issuecomment-1232203641) there because the [previous comment](https://github.com/iterate-ch/cyberduck/issues/13442#issuecomment-1208051030) described the situation in this issue (SSH key/no password).

Looking at [the fix](#13700) for the other issue, it can't impact this one because `credentials.isPasswordAuthentication()` will be false resulting in the same behaviour.

My comment from the other issue for convenience:

> Just another "me too" - using a private key & no password on macOS 12.5.1.
>
> I can ssh on the command line fine & I can access using FileZilla fine, but CyberDuck 8.4.3 fails with "Too many authentication failures."
>
> It works if I use version 8.3.2 without changing anything else (thanks @wtw!)

**Comment by dkocher** [comment]
Duplicate for #13680.

**Comment by manuel-koch** [comment]
I updated to Version 8.4.5 (38423) and then issue still happens. I can still access my server via console with plain ssh command but Cyberduck keeps complaining about "Too many authentication failures.".

**Comment by manuel-koch** [comment]
Upgraded to Version 8.5.0 (38556) and the issue seems to be solved with that version.

**Comment by dkocher** [comment]
> Upgraded to Version 8.5.0 (38556) and the issue seems to be solved with that version.

Probably fixed with #13821.

**Comment by asmaloney** [comment]
Unfortunately it still doesn't fix it for me. (macOS 12.6.1 now.)

I have both 8.3.2  & 8.5.0 running with exactly the same settings in the bookmark & the "Connection" setting for SFTP are all the same.

I can ssh on the command line fine & I can access using FileZilla fine, but CyberDuck 8.5.0 fails with "Too many authentication failures." It works if I use version 8.3.2.

**Comment by ylangisc** [comment]
@asmaloney Please provide a debug containing a login attempt.

**Comment by asmaloney** [comment]
Sure.

I snipped out the section dealing with the login attempt and redacted it:

<details>
  <summary>Log</summary>

```
2022-11-04 17:41:32,212 [Thread-33] DEBUG ch.cyberduck.core.KeychainLoginService - Validate login credentials for Host{protocol=Profile{parent=sftp, vendor=iterate GmbH, description=null, image=null}, region='null', port=64999, hostname='foo.com', credentials=Credentials{user='username', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=Local{path='/Users/username/.ssh/cert_name'}}, uuid='5aa55ec9-xxxx-yyyy-zzzz-bdf47afc156f', nickname='foo.com – SFTP', defaultpath='/home/username', workdir=null, custom=null, labels=null}
2022-11-04 17:41:32,215 [Thread-33] DEBUG ch.cyberduck.core.sftp.openssh.config.transport.OpenSshConfig - Found host match in SSH config:Host{patternsApplied=false, hostName='null', proxyJump='null', port=0, identityFile=Local{path='/Users/username/.ssh/id_rsa'}, identityAgent=null, user='null', preferredAuthentications='null', identitiesOnly=null, batchMode=null}
2022-11-04 17:41:32,222 [Thread-33] INFO  ch.cyberduck.core.proxy.SystemConfigurationProxy - No proxy configuration found for target ftp://foo.com:64999
2022-11-04 17:41:32,223 [Thread-33] DEBUG ch.cyberduck.core.sftp.openssh.config.transport.OpenSshConfig - Found host match in SSH config:Host{patternsApplied=false, hostName='null', proxyJump='null', port=0, identityFile=Local{path='/Users/username/.ssh/id_rsa'}, identityAgent=null, user='null', preferredAuthentications='null', identitiesOnly=null, batchMode=null}
2022-11-04 17:41:32,223 [Thread-33] DEBUG ch.cyberduck.core.threading.NamedThreadFactory - Create thread for runnable ch.cyberduck.core.Resolver$1@6f76661
2022-11-04 17:41:32,223 [Thread-33] DEBUG ch.cyberduck.core.Resolver - Waiting for resolving of foo.com
2022-11-04 17:41:32,224 [resolver-1] INFO  ch.cyberduck.core.Resolver - Resolved foo.com to xxx.yyy.zzz.42
2022-11-04 17:41:32,225 [resolver-1] DEBUG ch.cyberduck.core.threading.NamedThreadFactory - Finished execution of runnable ch.cyberduck.core.Resolver$1@6f76661
2022-11-04 17:41:32,225 [Thread-33] DEBUG ch.cyberduck.core.Session - Connection will open to Host{protocol=Profile{parent=sftp, vendor=iterate GmbH, description=null, image=null}, region='null', port=64999, hostname='foo.com', credentials=Credentials{user='username', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=Local{path='/Users/username/.ssh/cert_name'}}, uuid='5aa55ec9-xxxx-yyyy-zzzz-bdf47afc156f', nickname='foo.com – SFTP', defaultpath='/home/username', workdir=null, custom=null, labels=null}
2022-11-04 17:41:32,231 [Thread-33] INFO  net.schmizz.sshj.transport.random.JCERandom - Creating new SecureRandom.
2022-11-04 17:41:32,233 [Thread-33] DEBUG net.schmizz.sshj.transport.random.JCERandom - Random creation took 0 ms
2022-11-04 17:41:32,270 [Thread-33] DEBUG net.schmizz.sshj.DefaultConfig - Available cipher factories: [chacha20-poly1305@openssh.com, aes128-cbc, aes128-ctr, aes192-cbc, aes192-ctr, aes256-cbc, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com, blowfish-cbc, blowfish-ctr, cast128-cbc, cast128-ctr, idea-cbc, idea-ctr, serpent128-cbc, serpent128-ctr, serpent192-cbc, serpent192-ctr, serpent256-cbc, serpent256-ctr, 3des-cbc, 3des-ctr, twofish128-cbc, twofish128-ctr, twofish192-cbc, twofish192-ctr, twofish256-cbc, twofish256-ctr, twofish-cbc, arcfour, arcfour128, arcfour256]
2022-11-04 17:41:32,285 [Thread-33] DEBUG ch.cyberduck.core.sftp.openssh.config.transport.OpenSshConfig - Found host match in SSH config:Host{patternsApplied=false, hostName='null', proxyJump='null', port=0, identityFile=Local{path='/Users/username/.ssh/id_rsa'}, identityAgent=null, user='null', preferredAuthentications='null', identitiesOnly=null, batchMode=null}
2022-11-04 17:41:32,286 [Thread-33] DEBUG ch.cyberduck.core.sftp.openssh.config.transport.OpenSshConfig - Found host match in SSH config:Host{patternsApplied=false, hostName='null', proxyJump='null', port=0, identityFile=Local{path='/Users/username/.ssh/id_rsa'}, identityAgent=null, user='null', preferredAuthentications='null', identitiesOnly=null, batchMode=null}
2022-11-04 17:41:32,286 [Thread-33] INFO  ch.cyberduck.core.proxy.SystemConfigurationProxy - No proxy configuration found for target ftp://foo.com:64999
2022-11-04 17:41:32,296 [Thread-33] INFO  ch.cyberduck.core.socket.DefaultSocketConfigurator - Set timeout to 30000ms for socket Socket[unconnected]
2022-11-04 17:41:32,316 [Thread-33] INFO  net.schmizz.sshj.transport.TransportImpl - Client identity string: SSH-2.0-Cyberduck/8.5.0.38556 (Mac OS X/12.6.1) (x86_64)
2022-11-04 17:41:32,345 [Thread-33] INFO  net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
2022-11-04 17:41:32,346 [Thread-33] DEBUG net.schmizz.concurrent.Promise - Setting <<kex done>> to `null`
2022-11-04 17:41:32,346 [Thread-33] DEBUG net.schmizz.sshj.transport.KeyExchanger - Sending SSH_MSG_KEXINIT
2022-11-04 17:41:32,348 [Thread-33] DEBUG net.schmizz.concurrent.Promise - Setting <<kexinit sent>> to `SOME`
2022-11-04 17:41:32,348 [Thread-33] DEBUG net.schmizz.concurrent.Promise - Awaiting <<kex done>>
2022-11-04 17:41:32,365 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received SSH_MSG_KEXINIT
2022-11-04 17:41:32,366 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.transport.KeyExchanger - Negotiated algorithms: [ kex=curve25519-sha256; sig=ssh-ed25519; c2sCipher=chacha20-poly1305@openssh.com; s2cCipher=chacha20-poly1305@openssh.com; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=zlib@openssh.com; s2cComp=zlib@openssh.com;  ]
2022-11-04 17:41:32,366 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.transport.KeyExchanger - Trying to verify algorithms with ch.cyberduck.core.sftp.SFTPSession$2@1526a0b3
2022-11-04 17:41:32,366 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] INFO  ch.cyberduck.core.sftp.SFTPSession - Negotiated algorithms [ kex=curve25519-sha256; sig=ssh-ed25519; c2sCipher=chacha20-poly1305@openssh.com; s2cCipher=chacha20-poly1305@openssh.com; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=zlib@openssh.com; s2cComp=zlib@openssh.com;  ]
2022-11-04 17:41:32,378 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Sending SSH_MSG_KEXDH_INIT
2022-11-04 17:41:32,423 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received kex followup data
2022-11-04 17:41:32,423 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Received SSH_MSG_KEXDH_REPLY
2022-11-04 17:41:32,423 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.common.KeyType - Key algo: ssh-ed25519, Key curve: 25519, Key Len: 32
p: [80, -113, -112, 65, 102, 60, 30, -91, -30, -58, -119, 117, 106, -64, 92, 103, 82, -75, 100, 87, 2, 53, -118, -82, -123, 121, 43, 46, -55, 32, -63, -82]
2022-11-04 17:41:32,429 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.transport.KeyExchanger - Trying to verify host key with ch.cyberduck.core.sftp.SFTPSession$1@2a3e4732
2022-11-04 17:41:32,430 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.transport.KeyExchanger - Sending SSH_MSG_NEWKEYS
2022-11-04 17:41:32,430 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received SSH_MSG_NEWKEYS
2022-11-04 17:41:32,440 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.concurrent.Promise - Setting <<kexinit sent>> to `null`
2022-11-04 17:41:32,440 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.concurrent.Promise - Setting <<kex done>> to `SOME`
2022-11-04 17:41:32,440 [Thread-33] DEBUG net.schmizz.sshj.SSHClient - Key exchange took 0.094 seconds
2022-11-04 17:41:32,440 [Thread-33] DEBUG ch.cyberduck.core.Session - Connection did open to Host{protocol=Profile{parent=sftp, vendor=iterate GmbH, description=null, image=null}, region='null', port=64999, hostname='foo.com', credentials=Credentials{user='username', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=Local{path='/Users/username/.ssh/cert_name'}}, uuid='5aa55ec9-xxxx-yyyy-zzzz-bdf47afc156f', nickname='foo.com – SFTP', defaultpath='/home/username', workdir=null, custom=null, labels=null}
2022-11-04 17:41:32,440 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.transport.TransportImpl - Received SSH_MSG_EXT_INFO
2022-11-04 17:41:32,441 [Thread-33] DEBUG ch.cyberduck.core.KeychainLoginService - Attempt authentication for Host{protocol=Profile{parent=sftp, vendor=iterate GmbH, description=null, image=null}, region='null', port=64999, hostname='foo.com', credentials=Credentials{user='username', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=Local{path='/Users/username/.ssh/cert_name'}}, uuid='5aa55ec9-xxxx-yyyy-zzzz-bdf47afc156f', nickname='foo.com – SFTP', defaultpath='/home/username', workdir=null, custom=null, labels=null}
2022-11-04 17:41:32,441 [Thread-33] DEBUG ch.cyberduck.core.sftp.auth.SFTPNoneAuthentication - Login using none authentication with credentials Credentials{user='username', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=Local{path='/Users/username/.ssh/cert_name'}}
2022-11-04 17:41:32,442 [Thread-33] DEBUG net.schmizz.concurrent.Promise - Setting <<service accept>> to `null`
2022-11-04 17:41:32,442 [Thread-33] DEBUG net.schmizz.sshj.transport.TransportImpl - Sending SSH_MSG_SERVICE_REQUEST for ssh-userauth
2022-11-04 17:41:32,442 [Thread-33] DEBUG net.schmizz.concurrent.Promise - Awaiting <<service accept>>
2022-11-04 17:41:32,510 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.transport.TransportImpl - Setting active service to ssh-userauth
2022-11-04 17:41:32,510 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.concurrent.Promise - Setting <<service accept>> to `SOME`
2022-11-04 17:41:32,511 [Thread-33] DEBUG net.schmizz.concurrent.Promise - Setting <<authenticated>> to `null`
2022-11-04 17:41:32,511 [Thread-33] DEBUG net.schmizz.sshj.userauth.UserAuthImpl - Trying `none` auth...
2022-11-04 17:41:32,511 [Thread-33] DEBUG net.schmizz.concurrent.Promise - Awaiting <<authenticated>>
2022-11-04 17:41:32,532 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.concurrent.Promise - Setting <<authenticated>> to `false`
2022-11-04 17:41:32,532 [Thread-33] DEBUG net.schmizz.sshj.userauth.UserAuthImpl - `none` auth failed
2022-11-04 17:41:32,538 [Thread-33] DEBUG ch.cyberduck.core.sftp.openssh.config.transport.OpenSshConfig - Found host match in SSH config:Host{patternsApplied=false, hostName='null', proxyJump='null', port=0, identityFile=Local{path='/Users/username/.ssh/id_rsa'}, identityAgent=null, user='null', preferredAuthentications='null', identitiesOnly=null, batchMode=null}
2022-11-04 17:41:32,551 [Thread-33] DEBUG ch.cyberduck.core.sftp.openssh.config.transport.OpenSshConfig - Found host match in SSH config:Host{patternsApplied=false, hostName='null', proxyJump='null', port=0, identityFile=Local{path='/Users/username/.ssh/id_rsa'}, identityAgent=null, user='null', preferredAuthentications='null', identitiesOnly=null, batchMode=null}
2022-11-04 17:41:32,557 [Thread-33] DEBUG com.sun.jna.NativeLibrary - Looking for library 'c'
2022-11-04 17:41:32,558 [Thread-33] DEBUG com.sun.jna.NativeLibrary - Adding paths from jna.library.path: /Applications/Cyberduck.app/Contents/Frameworks
2022-11-04 17:41:32,558 [Thread-33] DEBUG com.sun.jna.NativeLibrary - Trying libc.dylib
2022-11-04 17:41:32,558 [Thread-33] DEBUG com.sun.jna.NativeLibrary - Found library 'c' at libc.dylib
2022-11-04 17:41:32,562 [Thread-33] DEBUG ch.cyberduck.core.sftp.openssh.config.transport.OpenSshConfig - Found host match in SSH config:Host{patternsApplied=false, hostName='null', proxyJump='null', port=0, identityFile=Local{path='/Users/username/.ssh/id_rsa'}, identityAgent=null, user='null', preferredAuthentications='null', identitiesOnly=null, batchMode=null}
2022-11-04 17:41:32,562 [Thread-33] DEBUG ch.cyberduck.core.sftp.SFTPSession - Attempt login with 4 authentication methods [ch.cyberduck.core.sftp.auth.SFTPAgentAuthentication@2084141, ch.cyberduck.core.sftp.auth.SFTPPublicKeyAuthentication@36cd4fa3, ch.cyberduck.core.sftp.auth.SFTPChallengeResponseAuthentication@185ba901, ch.cyberduck.core.sftp.auth.SFTPPasswordAuthentication@44815c48]
2022-11-04 17:41:32,562 [Thread-33] DEBUG ch.cyberduck.core.sftp.SFTPSession - Remaining authentication methods [publickey]
2022-11-04 17:41:32,562 [Thread-33] INFO  ch.cyberduck.core.sftp.SFTPSession - Attempt authentication with credentials Credentials{user='username', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=Local{path='/Users/username/.ssh/cert_name'}} and authentication method ch.cyberduck.core.sftp.auth.SFTPAgentAuthentication@2084141
2022-11-04 17:41:32,562 [Thread-33] DEBUG ch.cyberduck.core.sftp.auth.SFTPAgentAuthentication - Login using agent OpenSSHAgentAuthenticator{proxy=com.jcraft.jsch.agentproxy.AgentProxy@4c31fd0} for Host{protocol=Profile{parent=sftp, vendor=iterate GmbH, description=null, image=null}, region='null', port=64999, hostname='foo.com', credentials=Credentials{user='username', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=Local{path='/Users/username/.ssh/cert_name'}}, uuid='5aa55ec9-xxxx-yyyy-zzzz-bdf47afc156f', nickname='foo.com – SFTP', defaultpath='/home/username', workdir=null, custom=null, labels=null}
2022-11-04 17:41:32,562 [Thread-33] DEBUG ch.cyberduck.core.sftp.openssh.OpenSSHAgentAuthenticator - Retrieve identities from proxy com.jcraft.jsch.agentproxy.AgentProxy@4c31fd0
2022-11-04 17:41:32,563 [Thread-33] DEBUG ch.cyberduck.core.sftp.openssh.OpenSSHAgentAuthenticator - Found 4 identities
2022-11-04 17:41:32,563 [Thread-33] DEBUG ch.cyberduck.core.sftp.auth.SFTPAgentAuthentication - Matching identity /Users/username/.ssh/cert_name found
2022-11-04 17:41:32,563 [Thread-33] DEBUG net.schmizz.concurrent.Promise - Setting <<authenticated>> to `null`
2022-11-04 17:41:32,563 [Thread-33] DEBUG net.schmizz.sshj.userauth.UserAuthImpl - Trying `publickey` auth...
2022-11-04 17:41:32,563 [Thread-33] DEBUG com.jcraft.jsch.agentproxy.sshj.AuthAgent - Attempting authentication using agent identity /Users/username/.ssh/cert_name
2022-11-04 17:41:32,564 [Thread-33] DEBUG net.schmizz.concurrent.Promise - Awaiting <<authenticated>>
2022-11-04 17:41:32,595 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG com.jcraft.jsch.agentproxy.sshj.AuthAgent - Attempting authentication using agent identity /Users/username/.ssh/cert_name
2022-11-04 17:41:32,618 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG com.jcraft.jsch.agentproxy.sshj.AuthAgent - Attempting authentication using agent identity /Users/username/.ssh/cert_name
2022-11-04 17:41:32,638 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.concurrent.Promise - Setting <<authenticated>> to `false`
2022-11-04 17:41:32,638 [Thread-33] DEBUG net.schmizz.sshj.userauth.UserAuthImpl - `publickey` auth failed
2022-11-04 17:41:32,639 [Thread-33] WARN  ch.cyberduck.core.sftp.SFTPSession - Login refused with credentials Credentials{user='username', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=Local{path='/Users/username/.ssh/cert_name'}} and authentication method ch.cyberduck.core.sftp.auth.SFTPAgentAuthentication@2084141
2022-11-04 17:41:32,639 [Thread-33] DEBUG ch.cyberduck.core.sftp.SFTPSession - Remaining authentication methods [publickey]
2022-11-04 17:41:32,639 [Thread-33] INFO  ch.cyberduck.core.sftp.SFTPSession - Attempt authentication with credentials Credentials{user='username', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=Local{path='/Users/username/.ssh/cert_name'}} and authentication method ch.cyberduck.core.sftp.auth.SFTPPublicKeyAuthentication@36cd4fa3
2022-11-04 17:41:32,639 [Thread-33] DEBUG ch.cyberduck.core.sftp.auth.SFTPPublicKeyAuthentication - Login using public key authentication with credentials Credentials{user='username', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=Local{path='/Users/username/.ssh/cert_name'}}
2022-11-04 17:41:32,641 [Thread-33] INFO  ch.cyberduck.core.sftp.auth.SFTPPublicKeyAuthentication - Reading private key Local{path='/Users/username/.ssh/cert_name'} with key format OpenSSH
2022-11-04 17:41:32,659 [Thread-33] DEBUG net.schmizz.concurrent.Promise - Setting <<authenticated>> to `null`
2022-11-04 17:41:32,659 [Thread-33] DEBUG net.schmizz.sshj.userauth.UserAuthImpl - Trying `publickey` auth...
2022-11-04 17:41:32,659 [Thread-33] DEBUG net.schmizz.sshj.userauth.method.AuthPublickey - Attempting authentication using PKCS8KeyFile{resource=[PrivateKeyReaderResource] java.io.InputStreamReader@35a648aa}
2022-11-04 17:41:32,677 [Thread-33] DEBUG net.schmizz.concurrent.Promise - Awaiting <<authenticated>>
2022-11-04 17:41:32,698 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.userauth.method.AuthPublickey - Attempting authentication using PKCS8KeyFile{resource=[PrivateKeyReaderResource] java.io.InputStreamReader@35a648aa}
2022-11-04 17:41:32,719 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] DEBUG net.schmizz.sshj.userauth.method.AuthPublickey - Attempting authentication using PKCS8KeyFile{resource=[PrivateKeyReaderResource] java.io.InputStreamReader@35a648aa}
2022-11-04 17:41:32,740 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] INFO  net.schmizz.sshj.transport.TransportImpl - Received SSH_MSG_DISCONNECT (reason=PROTOCOL_ERROR, msg=Too many authentication failures)
2022-11-04 17:41:32,740 [sshj-Reader-foo.com/xxx.yyy.zzz.42:64999] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Too many authentication failures
net.schmizz.sshj.transport.TransportException: Too many authentication failures
	at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:533) ~[sshj-0.34.0.jar:?]
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:489) ~[sshj-0.34.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113) ~[sshj-0.34.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200) ~[sshj-0.34.0.jar:?]
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60) ~[sshj-0.34.0.jar:?]
```
</details>

**Comment by dkocher** [comment]
@asmaloney Please try the [configuration options documented](https://docs.cyberduck.io/protocols/sftp/#too-many-authentication-failures) to limit the number of authentication attempts or increase the number of allowed authentication attempts on the server.

**Comment by asmaloney** [comment]
I had run through (almost) all of these before.

1. The identity in the bookmark has always been set to `SSH Private Key`.
2. I can't change the servers.
3. `IdentitiesOnly` is now on in my config for `Host *`. (Though prior to this I had it commented out which seems to indicate I tried that but it either had no effect or broke something else.)
5. I'm not sure what some of these are: `gssapi-with-mic,hostbased,publickey,keyboard-interactive,password` so I don't know (and am hesitant) to change them in case it breaks something else. What order should they be in?

If I have the bookmark explicitly set to `SSH Private Key`without a password, should CyberDuck be trying anything else?

Thanks @dkocher!

**Comment by asmaloney** [comment]
Just another data point (related to (3) - I did turn it off for a reason):

If I turn on `IdentitiesOnly`, then I cannot connect with version 8.3.2 anymore. 🤔 

> Login failed. Exhausted available authentication methods.

**Comment by dkocher** [comment]
Support for public key file in IdentityFile directive with IdentitiesOnly was implemented with #13935.

**Comment by asmaloney** [comment]
Thanks for the update @dkocher.

Unfortunately 8.5.4 still doesn't work for me ("Login failed. Too many authentication failures") with or without `IdentitiesOnly` set.

**Comment by lzambarda** [comment]
Same for me with 8.5.5 on macOS 12.4. Had to switch to FileZilla to be able to connect.

**Comment by SwordJason** [comment]
I got a solution for myself

vi ~/.ssh/config

Add following config
```
Host * 
    IdentitiesOnly=yes
```
