### ISSUE TITLE
S3: Failure to read attributes of [filename] when copying new file from local to server - only happening in 9.1.3

### ISSUE THREAD

**Issue by MelTheFruitFly** [iterate-ch/cyberduck#17053]
Verified that this is not permissions. Error started happening when upgraded to 9.1.3. Issue is not present in 9.1.2 

### Describe the bug
After upgrading to 9.1.3 I cannot upload **new** files to the S3 server from my local device. I am able to create a file on the server using the right click new file option or upload a new version of an existing file to overwrite, but if I try to upload a file that doesn't already exist on the server, I get the error `Failure to read attributes of [filename]`. 

My permissions have not changed. After working with my team to ensure there had been no changes to my permissions, downgraded. 

After I downgraded to 9.1.2, I am able to upload new files again. 

Just to double check, upgraded to 9.1.3 again, got the error again. 

### To Reproduce
Steps to reproduce the behavior using v 9.1.3:
1. Connect to S3 server to a folder where you have full permission. 
2. Drag and drop OR choose to upload and browse to the file, selecting a file that does not already exist on the server 
3. Receive error 

**Workaround**
In 9.1.3, if you right click to create the file on the server using the exact filename that exists on local, then upload or drag and drop, it will allow you to overwrite that file. 

**Expected behavior**
I expect the same thing to happen as does in 9.1.2, which is to upload a new file. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Sequoia 15.4.1

**Log Files**
[cyberduck.log](https://github.com/user-attachments/files/19855705/cyberduck.log)

Log is uploading a file successfully on 9.1.2, deleting that file, then upgrading to 9.1.3, trying to upload that file again and getting error.

**Comment by dkocher** [comment]
Possibly fixed with #16981. @MelTheFruitFly Can you reproduce with the current [snapshot build](https://docs.cyberduck.io/cyberduck/preferences/#snapshot-builds)?

**Comment by dkocher** [comment]
The credentials used are missing permission to retrieve files from the bucket `helpscout.net` it appears.

```
2025-04-22 15:11:38,624 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.request - HEAD /docs/assets/mp4/304-purge_cropped%20copy.mp4 HTTP/1.1
2025-04-22 15:11:38,624 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.request - Host: helpscout.net.s3.dualstack.us-east-1.amazonaws.com
2025-04-22 15:11:38,624 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.request - Connection: Keep-Alive
2025-04-22 15:11:38,624 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.request - User-Agent: Cyberduck/9.1.3.42945 (Mac OS X/15.4.1) (aarch64)
2025-04-22 15:11:38,624 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.request - Accept-Encoding: gzip,deflate
2025-04-22 15:11:38,624 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.request - x-amz-date: 20250422T191138Z
2025-04-22 15:11:38,624 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.request - x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2025-04-22 15:11:38,624 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.request - Authorization: ********
2025-04-22 15:11:38,659 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.response - HTTP/1.1 403 Forbidden
2025-04-22 15:11:38,659 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.response - x-amz-request-id: XPZ90GDPV8MS0WKY
2025-04-22 15:11:38,659 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.response - x-amz-id-2: qFIPwq7o0poTDW4PeYIidpMyRv3hf+lF/KHZuK+VNXEkMOiksOYoqY3DwyLSMTe3OfF/jCB3I5OxbPkOs2Q5fn7/RvousHcq
2025-04-22 15:11:38,659 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.response - Content-Type: application/xml
2025-04-22 15:11:38,659 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.response - Transfer-Encoding: chunked
2025-04-22 15:11:38,659 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.response - Date: Tue, 22 Apr 2025 19:11:38 GMT
2025-04-22 15:11:38,659 [zWCRcQEH-transfer-1] INFO  ch.cyberduck.transcript.response - Server: AmazonS3
```

**Comment by MelTheFruitFly** [comment]
> Possibly fixed with [#16981](https://github.com/iterate-ch/cyberduck/pull/16981). [@MelTheFruitFly](https://github.com/MelTheFruitFly) Can you reproduce with the current [snapshot build](https://docs.cyberduck.io/cyberduck/preferences/#snapshot-builds)?

@dkocher Unfortunately yes it's still happening in the latest snapshot build - 9.1.4 43141

Log from this attempt attached

[cyberduck.log](https://github.com/user-attachments/files/19876388/cyberduck.log)

**Comment by dkocher** [comment]
@MelTheFruitFly Can you attach a log from a successful transfer using version 9.1.2 where the upload succeeds.

**Comment by MelTheFruitFly** [comment]
Sure thing -- attached. 

[cyberduck.log](https://github.com/user-attachments/files/19980516/cyberduck.log)

**Comment by dkocher** [comment]
This looks like a duplicate of #16939. Can you double check if the issue is resolved by updating to the 9.1.4 release build _9.1.4.43177_.

**Comment by MelTheFruitFly** [comment]
@dkocher - Unfortunately no go on 9.1.4.43177 either. Log for this try attached. 

[cyberduck.log](https://github.com/user-attachments/files/20039527/cyberduck.log)

I also tried the most recent snapshot just for giggles, and that also didn't work but I didn't save the log for it but I'd assume same problem.
